name: Build and Push to Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    name: Build, Push and Deploy ECS Fargate
    runs-on: ubuntu-latest

    steps:
      #################################################
      # 1. Checkout do código
      #################################################

      - name: Checkout code
        uses: actions/checkout@v4

      #################################################
      # 2. Configurar Java
      #################################################

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      #################################################
      # 3. Testes unitários
      #################################################

      - name: Execute unit tests
        run: mvn test

      #################################################
      # 4. Login no Docker Hub
      #################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #################################################
      # 5. Build e Push da imagem
      #################################################

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pix-simulator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pix-simulator:${{ github.sha }}

      #################################################
      # 6. Credenciais AWS
      #################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #################################################
      # 7. Setup Terraform
      #################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #################################################
      # 8. Terraform Apply
      #################################################

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve

      #################################################
      # 9. Force New Deployment no ECS Fargate
      #################################################

      - name: Force New ECS Deployment
        run: |
          aws ecs update-service \
            --cluster pix-simulator-cluster \
            --service pix-simulator-service \
            --force-new-deployment

      #################################################
      # 10. Mostrar URL do Load Balancer
      #################################################

      - name: Get Load Balancer URL
        run: |
          echo "Buscando DNS do Application Load Balancer..."

          ALB_DNS=$(aws elbv2 describe-load-balancers \
            --query "LoadBalancers[?contains(LoadBalancerName, 'pix-simulator')].DNSName" \
            --output text)

          echo "------------------------------------------------"
          echo "LINK DA SUA APLICAÇÃO:"
          echo "http://$ALB_DNS"
          echo "------------------------------------------------"