name: Terraform Destroy ECS Fargate

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      #################################################
      # 1. Checkout do código
      #################################################

      - name: Checkout code
        uses: actions/checkout@v4

      #################################################
      # 2. Configurar credenciais AWS
      #################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #################################################
      # 3. Escalar ECS Service para 0 (boa prática)
      #################################################

      - name: Scale ECS Service to Zero
        run: |
          aws ecs update-service \
            --cluster pix-simulator-cluster \
            --service pix-simulator-service \
            --desired-count 0 || true

      #################################################
      # 4. Aguardar estabilização
      #################################################

      - name: Wait ECS Service Stabilization
        run: |
          echo "Aguardando ECS finalizar as tasks..."
          sleep 30

      #################################################
      # 5. Setup Terraform
      #################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #################################################
      # 6. Terraform Destroy
      #################################################

      - name: Terraform Init and Destroy
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform destroy -auto-approve